# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: schubert-da/the-living-grid
  skip_ci: true

media_folder: /static/media
public_folder: /media

collections:
  - name: posts
    label: Posts
    folder: src/content/posts
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Body, name: body, widget: markdown }
