# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: schubert-da/the-living-grid
  skip_ci: true

media_folder: /static/media
public_folder: /media

media_libraries:
  default:
    config:
      transformations:
        raster_image: # original format
          format: webp # new format, only `webp` is supported
          quality: 85 # default: 85
          width: 500 # default: original size
          height: 500 # default: original size

collections:
  - name: posts
    label: Posts
    folder: src/content/posts
    format: json
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Body Content, name: body-content, widget: markdown }
  - name: images
    label: Gallery Images
    folder: src/content/image-gallery
    format: json
    fields:
      - { label: Title, name: title, widget: string }
      - {
          label: Description,
          name: description,
          widget: string,
          required: false,
        }
      - { label: Image, name: image, widget: image, multiple: true, max: 5 }
      - { label: Location, name: location, widget: string, required: false }
      - {
          label: Upload date,
          name: date,
          widget: datetime,
          picker_utc: true,
          default: "{{now}}",
        }
      - { label: Tags, name: tags, widget: list }
